### ISSUE TITLE
Plugin published with non-standard version format

### ISSUE THREAD

**Issue by mnazbro** [palantir/gradle-miniconda-plugin#14]
Right now the version that is returned is prefixed with a "v" (e.g. `v0.3.1`. Since the publishPlugins task just reads directly from `version`, we would need to either change the versioning tags or change the way we read the version from the `com.palantir.git-version` plugin to drop the leading v.

**Comment by punya** [comment]
Thanks for flagging. I'd prefer to just change the tag naming scheme.

**Comment by punya** [comment]
[Tagged](https://github.com/palantir/gradle-miniconda-plugin/releases/tag/0.3.2), [built](https://circleci.com/gh/palantir/gradle-miniconda-plugin/30) and [published](https://plugins.gradle.org/plugin/com.palantir.python.miniconda/0.3.2) `0.3.2` without the leading `v`.
