### ISSUE TITLE
Fails with Gradle 2.11 - ModuleDependency.artifact

### ISSUE THREAD

**Issue by bzamecnik** [palantir/gradle-miniconda-plugin#48]
In Gradle 2.11 it fails, in Gradle 3.1 it works perfectly.

```
$ ./gradlew

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'python-miniconda'.
> Failed to notify dependency resolution listener.
   > org.gradle.api.artifacts.ModuleDependency.artifact(Lorg/gradle/api/Action;)Lorg/gradle/api/artifacts/DependencyArtifact;
```

Minimal failing `build.gradle`:

```
plugins {
  id 'com.palantir.python.miniconda' version '0.7.0'
}

miniconda {
    minicondaVersion = '4.3.11'
    packages = ['python']
    pythonVersion = 2
    channels = ['https://repo.continuum.io/pkgs/free']
}
```

**Comment by mnazbro** [comment]
The latest version of this plugin supports Gradle 3.1 or greater. It's built with Gradle 3.1 (See https://github.com/palantir/gradle-miniconda-plugin/blob/develop/gradle/wrapper/gradle-wrapper.properties#L6). It's difficult to provide backwards compatibility with Gradle plugins without building in that version, so Gradle 2.11 is not supported.
